### ISSUE TITLE
Upgrading @swc/core from 1.3.4 to >= 1.3.5 causes all tests to fail

### ISSUE THREAD

**Issue by jnarwold** [swc-project/jest#128]
In upgrading `@swc/core` from `1.3.4` to `1.3.5`, all of our tests fail with the same error:

```
  ● Test suite failed to run

    failed to process input file

    Caused by:
        cannot process file because it's ignored by .swcrc

      at Compiler.transformSync (../../../node_modules/.pnpm/@swc+core@1.3.5/node_modules/@swc/core/index.js:241:29)
      at transformSync (../../../node_modules/.pnpm/@swc+core@1.3.5/node_modules/@swc/core/index.js:348:21)
      at Object.process (../../../node_modules/.pnpm/@swc+jest@0.2.23_@swc+core@1.3.5/node_modules/@swc/jest/index.js:73:45)
      at ScriptTransformer.transformSource (../../../node_modules/.pnpm/@jest+transform@27.5.1/node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (../../../node_modules/.pnpm/@jest+transform@27.5.1/node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (../../../node_modules/.pnpm/@jest+transform@27.5.1/node_modules/@jest/transform/build/ScriptTransformer.js:822:19)
```

**Comment by kdy1** [comment]
Please file an issue on main repo with repro case

2022년 11월 3일 (목) 오전 10:29, Joel Narwold ***@***.***>님이 작성:
