### ISSUE TITLE
Methods are not polyfilled with core-js

### ISSUE THREAD

**Issue by gu-stav** [swc-project/jest#132]
In the swc playground I can see that specifying `"env": { "mode": "usage", "coreJs": "3.26.1" }` does include polyfills from `core-js`: [Playground](https://play.swc.rs/?version=1.3.17&code=H4sIAAAAAAAAA1MvSS0uUdcrSi3ISUxOdczJ0VBX11FQV9e05lI31DPSM1bXKy7IySzRUNdT19RLLNHQNQRKRRsaGceCeCAOAG324sZDAAAA&config=H4sIAAAAAAAAA0WOSwrDMAxE76J1CE1Ks8gRCj2EcJXg4h%2BSUxqC7165uGQnzbwZ6YCXGJgPSMhCXCfZQ8YPzEDGoxi2KUOnmEoLOqHSQUZeKVdExstwU9vFKNSADrwNdtlrmYk%2BMYmcFobV%2FcmiXT4%2BtyockPdEv84JytnRclYeDcy86U7hXTOarplNcCV9w0Smux6Daz9O%2FQClfAHo9O9N4QAAAA%3D%3D)

This doesn't seem to work in `swc/jest` and e.g. specifying a `target` doesn't help either. When running a test e.g. in `node@14` I get the follwing error:

```
TypeError: data.replaceAll is not a function

      14 |
      15 | const PreviewWysiwyg = ({ data }) => {
    > 16 |   const html = useMemo(() => sanitizeHtml(md.render(data.replaceAll('\\n', '\n') || '')), [data]);
         |                                                          ^
      17 |
      18 |   return (
      19 |     <Wrapper>

      at replaceAll (packages/core/admin/admin/src/content-manager/components/PreviewWysiwyg/index.js:16:58)
      at mountMemo (node_modules/react-dom/cjs/react-dom.development.js:15846:19)
      at Object.useMemo (node_modules/react-dom/cjs/react-dom.development.js:16219:16)
      at useMemo (node_modules/react/cjs/react.development.js:1532:21)
      at PreviewWysiwyg (packages/core/admin/admin/src/content-manager/components/PreviewWysiwyg/index.js:16:23)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17811:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19049:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
```

The same would happen for e.g. `.at()`.

Complete setup: https://github.com/strapi/strapi/blob/main/jest.base-config.front.js#L56-L71
Follow up of https://github.com/swc-project/swc/issues/6460

**Comment by kdy1** [comment]
Closing in favor of https://github.com/swc-project/swc/issues/6460
