### ISSUE TITLE
Jest 28/29 compatibility (swc errors)

### ISSUE THREAD

**Issue by bsk26** [swc-project/jest#135]
We're seeing SWC errors when upgrading from jest `27` to `28` or `29`,

```
    Caused by:
        Missing export __get_transform_plugin_core_pkg_diag
```

This appears to be an error in SWC, and `@swc/jest`'s `package.json` has a `devDependency` on jest `27` so it seems plausible that upgrading is the issue (https://github.com/swc-project/jest/blob/e35cadd1eb6768917073de5ec1f95b4d2e7993f3/package.json#L38)

Here's the full stack trace:
```

    Caused by:
        Missing export __get_transform_plugin_core_pkg_diag

      51 |             swcTransformer.process = function tracedProcess(sourceText, sourcePath, options) {
      52 |                 const processStart = process.hrtime();
    > 53 |                 const ret = origProcess.call(this, sourceText, sourcePath, options);
         |                                         ^
      54 |                 const processComplete = process.hrtime(processStart);
      55 |                 log(processComplete, sourcePath);
      56 |                 return ret;

      at Compiler.transformSync (../node_modules/@swc/core/index.js:241:29)
      at transformSync (../node_modules/@swc/core/index.js:348:21)
      at Object.process (../node_modules/@swc/jest/index.js:73:45)
      ...
      at ScriptTransformer.transformSource (../node_modules/@jest/transform/build/ScriptTransformer.js:519:31)
      at revertHook.exts (../node_modules/@jest/transform/build/ScriptTransformer.js:750:18)
      at Module._compile (../node_modules/pirates/lib/index.js:130:29)
      at Object.newLoader (../node_modules/pirates/lib/index.js:141:7)
```

**Comment by kwonoj** [comment]
👋 long time no see

This error is not coming from jest upgrade, it's due to interface difference between plugin's sdk vs. `@swc/core`. Best bet is trying to upgrade `swc_core` for the plugin, and use latest `@swc/core` for matching sdk.

**Comment by bsk26** [comment]
@kwonoj thanks for the quick reply: you're right, the issue we're seeing was related to me errantly upgrading `@swc/core`. Reverted this upgrading and things are working with jest 28!
