### ISSUE TITLE
unknown variant `es2023`, expected one of `es3`, ...

### ISSUE THREAD

**Issue by HansAarneLiblik** [swc-project/jest#145]
After upgrading to @swc/jest to v0.2.25, my testsuite is full of errors

> FAIL src/app/core/elements/link/Link.test.ts
  ● Test suite failed to run
    Failed to deserialize buffer as swc::config::Options
    JSON: {"jsc":{"transform":{"react":{"runtime":"automatic"},"hidden":{"jest":true}},"target":"es2023"},"sourceMaps":"inline","module":{"type":"commonjs"},"filename":"/app/react/src/app/core/elements/link/Link.test.ts"}
    Caused by:
        unknown variant `es2023`, expected one of `es3`, `es5`, `es2015`, `es2016`, `es2017`, `es2018`, `es2019`, `es2020`, `es2021`, `es2022`, `esnext` at line 1 column 217
      at Compiler.transformSync (node_modules/@swc/core/index.js:241:29)
      at transformSync (node_modules/@swc/core/index.js:348:21)
      at Object.process (node_modules/@swc/jest/index.js:73:45)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:542:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:671:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:723:19)

**Comment by HansAarneLiblik** [comment]
Thanks for the speedy fix!

**Comment by TomONeill** [comment]
Not really a fix though... I am using a ES2023 feature which compiles and runs fine, but my jest test is now failing because it is not supported...
When do you expect to add support for it?
