### ISSUE TITLE
ReferenceError: React is not defined with tsx

### ISSUE THREAD

**Issue by nallwhy** [swc-project/jest#167]
With the NestJS application https://github.com/nallwhy/nest_sample/commit/87041662c284b35fba664edccc6da1532953818f

when I run a test
```
npx jest --testPathPattern /Users/json/workspace/study/nest_sample/src/template\.spec\.ts
```

I get the error below
```
 FAIL  src/template.spec.ts
  ● Test suite failed to run

    Cannot find module 'react/jsx-runtime' from 'template.tsx'

    Require stack:
      template.tsx
      template.spec.ts



      at Resolver._throwModNotFoundError (../node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (template.tsx:11:21)
```

This project uses jsx(via [jsxte](https://github.com/ncpa0/jsxte)) but not React.

I applied options below to `tsconfig.json` for compiling jsx without React.

```json
{
  "compilerOptions": {
    ...
    "jsx": "react-jsx",
    "jsxImportSource": "jsxte"
  }
}

```

But I can't setup like this with `@swc/jest`.

**Comment by nallwhy** [comment]
I solved it with https://swc.rs/docs/configuration/compilation#jsctransformreactimportsource.
Sorry.
