### ISSUE TITLE
fix(for-in): cannot use for-in in async callback of "it"(=="test")

### ISSUE THREAD

**Issue by jjangga0214** [swc-project/jest#17]
Hi!

Thanks for this awesome package!

The following code throws an error.

```ts
describe('foo', () => {
  it('bar', async () => {
    const obj = { hi: 'there' }
    for (const qux in obj) {
        console.log(qux)
    }
    expect(await Promise.resolve(1)).toStrictEqual(1)
  })
})

```

```
ReferenceError: qux is not defined

      at _callee$ (test/index.test.ts:47:25)
      at tryCatch (../../node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (../../node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (../../node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (test/index.test.ts:5:28)
      at _next (test/index.test.ts:23:17)
      at test/index.test.ts:28:13
      at Object.<anonymous> (test/index.test.ts:20:16)
```

This happens when 1) `for-in` is used, AND 2) called in `async  callback of "it"(=="test")`.

I tested the same code with [ts-jest](https://www.npmjs.com/package/ts-jest), but it worked.
I tested a "similar"(`for-in` in async function, but not with jest) code with `swc`, and it worked as well.

Thus I think this is a bug of either `@swc/jest` or `regenerator-runtime`, how do you think?

I personally guess it can probably be caused by `regenerator-runtime` 's fault, but decided to report this behavior here first.

Thanks!

**Info**:
- "regenerator-runtime": "^0.13.9"
- "@swc/core": "^1.2.66"
- "@swc/helpers": "^0.2.12"
- "@swc/jest": "^0.1.4"
- jest: 27.0.6
- typescript: 4.3.5
- node: v16.1.0
- os: ubuntu 20.04

**Comment by kdy1** [comment]
I think this is fixed in latest version.
