### ISSUE TITLE
puppeteer: ReferenceError: navigate is not defined

### ISSUE THREAD

**Issue by Janpot** [swc-project/jest#42]
It looks like `@swc/jest` has trouble transforming the puppeteer package

## Reproduction:
Initialize project
```sh
yarn init --yes
yarn add -D puppeteer jest @types/jest @swc/jest @swc/core regenerator-runtime
```
Add `jest.config.js`
```ts
// jest.config.js
module.exports = {
  transform: {
    "^.+\\.(t|j)sx?$": "@swc/jest",
  },
  transformIgnorePatterns: [],
};
```
Add following test
```ts
// index.spec.ts
import puppeteer from "puppeteer";

test("hello", async () => {
  const browser = await puppeteer.launch();
  try {
    const page = await browser.newPage();
    await page.goto("https://www.google.com");
  } finally {
    await browser.close();
  }
});
```
Run
```sh
npx jest
```
Observe
```
 FAIL  ./index.spec.ts
  ✕ hello (2025 ms)

  ● hello

    ReferenceError: navigate is not defined

      at FrameManager._callee$ (node_modules/puppeteer/src/common/FrameManager.ts:493:44)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:49:25)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:175:30)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:77:29)
      at asyncGeneratorStep (node_modules/puppeteer/src/common/FrameManager.ts:20:1)
      at _next (node_modules/puppeteer/src/common/FrameManager.ts:57:3)
      at node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:45:13
      at node_modules/puppeteer/src/common/FrameManager.ts:54:3
      at FrameManager.navigateFrame (node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:398:31)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.258 s, estimated 6 s
Ran all test suites.
```
## Expected behavior

Now change in `jest.config.js`:

```ts
  transformIgnorePatterns: ['/node_modules/puppeteer/.+\\.js$'],
```
And run again
```
npx jest
```

Observe

```
 PASS  ./index.spec.ts
  ✓ hello (2763 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.009 s
Ran all test suites.
```

## Environment

```
@swc/core@1.2.111
@swc/jest@0.2.5
jest@27.3.1
puppeteer@11.0.0
node: v16.13.0
```

**Comment by kdy1** [comment]
I expect this to be fixed
