### ISSUE TITLE
unknown field `sourceMaps`

### ISSUE THREAD

**Issue by joshyudeep** [swc-project/jest#47]
Not sure how to fix this... Any help appreciated! 🙏 

### Environment:
```
"@swc/core": "1.2.112",
"@swc/jest": "0.2.8",
```

### .swcrc config
```
{
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dynamicImport": true,
      "decorators": false
    },
    "transform": {
      "react": {
        "pragma": "React.createElement",
        "pragmaFrag": "React.Fragment",
        "throwIfNamespace": true,
        "development": false,
        "useBuiltins": false
      }
    },
    "target": "es2015",
    "loose": false,
    "externalHelpers": false,
    "keepClassNames": false,
    "sourceMaps": true
  }
}

```

### Failure
```
  ● Test suite failed to run

    failed to process js file

    Caused by:
        0: failed to read swcrc file (/Users/joyu/Development/lending/frontend/borrower/test/jestSetup.js)
        1: failed to deserialize .swcrc (json) file: unmatched data: 25:16
        2: unknown field `sourceMaps`, expected one of `parser`, `transform`, `externalHelpers`, `target`, `loose`, `keepClassNames`, `baseUrl`, `paths`, `minify`, `experimental` at line 25 column 16

      at Compiler.transformSync (node_modules/@swc/core/index.js:135:25)
      at Object.transformSync (node_modules/@swc/core/index.js:215:21)
      at Object.process (node_modules/@swc/jest/index.js:68:27)
```

**Comment by srmagura** [comment]
The `sourceMaps` key should not be nested under `jsc`. It needs to be at the top level. 🙂

For example:

```json
{
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": true,
            "dynamicImport": true
        },
        "target": "es2021"
    },
    "module": {
        "type": "commonjs"
    },
    "sourceMaps": true
}
```

**Comment by joshyudeep** [comment]
thanks so much! 🤦 🤦 🤦 🤦 🤦  lol.
