### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'sourceMaps')

### ISSUE THREAD

**Issue by jkamzi** [swc-project/jest#67]
A recent pull request https://github.com/swc-project/jest/pull/66

This pull request set `sourceMaps` to `true` by default.  This will cause the following error:

```
    TypeError: Cannot set properties of undefined (setting 'sourceMaps')

      at set (node_modules/@swc/jest/index.js:113:12)
      at Object.process (node_modules/@swc/jest/index.js:69:17)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:620:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:766:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:823:19)

```
(Example repo: https://github.com/jkamzi/swc-jest-transform-opts-undefined)

The issue comes from:

https://github.com/swc-project/jest/blob/f05ee1e160716dadbc7d6ce310c375a5b476a15e/index.ts#L48-L50

`swcTransformOpts` can be undefined, and the above if statement do not account for that, and when `set` is called it will throw a `TypeError`. [Typescript playground link to demonstrate this](https://www.typescriptlang.org/play?#code/C4TwDgpgBAyg9gWwgFXNAvFA3gKClAQwH4AuKAIzjgBsICA7AbhwF8ccAzAV3oGNgAlnHpQAJnHhJgACwH0A5gAo45AFZlJKNFAA+UHqIgc5EUQEpseKAI5RFAQhWqiAOgIXc+fAHpvUXsIAzjQQLtRwShYA7gLU1FAATjxQEABuECI2UE7Wgfr0hsb0plb4AfTBtGERigDkADJUANZ51AJN0E4Q-FBRBHmBEMC1Zsz4bGw44poyckoGRibmjEA)

**Comment by kdy1** [comment]
Thank you for reporting!
I published a new version.
