### ISSUE TITLE
Top-level await results in `await is not defined`

### ISSUE THREAD

**Issue by millsp** [swc-project/jest#82]
Top-level await does not seem to work out of the box. I have tried to enable it in `jsc.parser.topLevelAwait = true` but that did not change anything. @kdy1 Do you know if this is a bug or a configuration issue?

I also tried setting the target to `es2018` and the module type to `es6` with the other settings, but that did not help. We are using this in a TypeScript setup.

**Comment by millsp** [comment]
Nevermind, adding seems to unlock but the next problem is
```ts
module.exports = {
  // ...
  extensionsToTreatAsEsm: ['.ts', '.tsx'],
}
```

I'm not sure why the following is happening:
```ts
Details:

    /home/millsp/Work/prisma/packages/sdk/dist/cli/getSchema.js:30
    import regeneratorRuntime from "regenerator-runtime";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      94 | });
      95 | var import_getGeneratorSuccessMessage = __toModule(require("./cli/getGeneratorSuccessMessage"));
    > 96 | var import_getSchema = __toModule(require("./cli/getSchema"));
         |                                   ^
      97 | var import_hashes = __toModule(require("./cli/hashes"));
      98 | var import_Help = __toModule(require("./cli/Help"));
      99 | var import_Help2 = __toModule(require("./cli/Help"));

      at Runtime.createScriptFromCode (../../../node_modules/.pnpm/jest-runtime@27.5.1/node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (../../sdk/dist/index.js:96:35)
```

**Comment by kdy1** [comment]
It's not an issue of SWC

**Comment by kdy1** [comment]
The error is thrown by nodejs
