### ISSUE TITLE
path transformation not working properly

### ISSUE THREAD

**Issue by luanglopes** [swc-project/jest#96]
Having problems when running tests and using paths aliases

when I run tests with `jest` I get this error:
```bash
> teste-node-app@1.0.0 test
> jest

 FAIL  src/app/useCases/Login/DbLogin.spec.ts
  ● Test suite failed to run

    Cannot find module './src/shared/Result' from 'src/app/useCases/Login/DbLogin.spec.ts'

      1 | import { User } from '@/domain/entities/User'
    > 2 | import { Result } from '@/shared/Result'
        |                                         ^
      3 |
      4 | import { DbLogin } from './DbLogin'
      5 | import { InvalidCredentialsError, LoadUserByUsernameRepository, LoginInputDTO } from './protocols'

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (src/app/useCases/Login/DbLogin.spec.ts:2:41)
```

focus on line where it says:
```bash
Cannot find module './src/shared/Result' from 'src/app/useCases/Login/DbLogin.spec.ts'
```

It seems that it is transforming the path as if it the test file was at the root of the project

jest.config.js file:
```javascript
export default {
  clearMocks: true,
  collectCoverage: true,
  coverageDirectory: "coverage",
  coverageProvider: "v8",
  transform: {
    "^.+\\.(t|j)s$": ["@swc/jest"],
  },
};
```

.swcrc file:
```json
{
  "env": {
    "targets": {
      "node": 16
    }
  },
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "module": {
    "type": "es6"
  }
}
```

tsconfig.json file:
```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Node 16",
  "compilerOptions": {
    "lib": ["ES2021"],
    "module": "ESNext",
    "target": "ESNext",
    "resolveJsonModule": true,
    "strict": true,
    "noUnusedLocals": true,
    "noEmitOnError": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "outDir": "build",
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["src/**/*.ts"]
}
```
package.json file:
```json
{
  ...
  "type": "module",
  "scripts": {
    ...
    "test": "jest"
  }
  ...
}
```

folder structure:

![image](https://user-images.githubusercontent.com/11901944/168216073-744ad8f6-124d-4e0e-afdf-9e974cac22cc.png)

P.S.: The build works and transform paths properly

**Comment by kdy1** [comment]
I think this will be fixed by the next version

**Comment by luanglopes** [comment]
> Can you try the latest `@swc/core`?

same problem

**Comment by esimons** [comment]
I'm also seeing issues with path transform in @swc/core: 1.2.186 and @swc/jest: 0.2.21
Pushed a repro of the issue here: https://github.com/esimons/swc-jest-baseUrl

Agree that swc build output shows expected transformation, it's just during jest testing that the issue appears. From the error messaging, it looks like the baseUrl is being substituted literally rather than used as path of a relative path resolution.

```
 FAIL  __tests__/b.test.js
  ● Test suite failed to run

    Cannot find module './src/./b' from '__tests__/b.test.js'

    > 1 | import b from "@/b";
        |                    ^
      2 |
      3 | it("returns 'boo'", () => {
      4 |     expect(b()).toBe("boo");

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (__tests__/b.test.js:1:20)

 FAIL  __tests__/a.test.js
  ● Test suite failed to run

    Cannot find module './src/./a' from '__tests__/a.test.js'

    > 1 | import a from "@/a";
        |                    ^
      2 |
      3 | it("returns 'boo'", () => {
      4 |     expect(a()).toBe("boo");

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (__tests__/a.test.js:1:20)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.324 s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by esimons** [comment]
One more note, it looks like if you change the `baseUrl` to be an absolute dir path then everything works as expected. So might be that when running swc in context of jest transform it's losing reference to the cwd / project root.

**Comment by luanglopes** [comment]
I got it working with:
`@swc/cli`: ^0.1.57`
`@swc/core: ^1.2.194`
`@swc/jest: ^0.2.21`
so I will close this issue
