### ISSUE TITLE
Test suite failing to run due to parsing error for upstream dependency

### ISSUE THREAD

**Issue by mn-prp** [swc-project/jest#98]
I have a typescript project that uses visx, a d3-based visualization library. And the tests for this project are failing to run due to a parse error while reading a d3 file:

```
 × Expected ':', got ')'
         ╭─[/Users/mnelson/test/testing-failure/node_modules/d3-array/dist/d3-array.js:140:5]
     140 │ : v => (sum += +valueof(v, index++, values) || 0));
         ·                                                  ─
         ╰────


    Caused by:
        0: failed to process input file
        1: Syntax Error

      at Compiler.transformSync (node_modules/@swc/core/index.js:137:25)
      at transformSync (node_modules/@swc/core/index.js:217:21)
      at Object.process (node_modules/@swc/jest/index.js:71:45)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:822:19)
```

I have tried adding this file to my jest-config's `transformIgnorePatterns`, but that does not solve the problem. When I switch my jest config to use ts-jest for transforming files, the tests pass. But they fail with @swc/jest. 

I've created a simple reproduction in this repository. The first commit shows the tests passing with ts-jest, the most recent commit shows them failing with @swc/jest. https://github.com/mn-prp/bug-example/

**Comment by HEHOHADA** [comment]
@mn-prp  by removing
 ```
parser: {
                         syntax: "typescript",
                         tsx: true
                     },
```
everything starts working in your repository

**Comment by mn-prp** [comment]
@HEHOHADA You're right. That solves the problem. Thanks!

**Comment by leonardomaier** [comment]
@HEHOHADA @mn-prp any idea on why removing it solves the problem?
